### ISSUE TITLE
第八章的连接和第九章重复了

### ISSUE THREAD

**Issue by WjF1991** [gf-huanchupk/SpringBootLearning#5]
应该是这个吧
https://mp.weixin.qq.com/s?__biz=MzI0NTYzMjM0Ng==&mid=100000094&idx=1&sn=be20921fd0a7cf20f491f365b896a9bc&chksm=694add6b5e3d547da64a36a593cdfeb4558ed554d03a0670dba0bc70344e9abcba4b14ccd195&mpshare=1&scene=1&srcid=1204dmLNmim2zGlI5K8DgyuG&sharer_sharetime=1575450432220&sharer_shareid=96fceb75db74f0745c6e52b9890d44e2&key=080c97357aa5fdf79c542ef68d1024304d4dafec7fc92a3c630e469420b9d2c937f2219567a799ac85c1991a56156e137838c050a250a73049e544d9211893c2049e0559953e04e398da64c62b96be4d&ascene=1&uin=Mzk1NTczOTE1&devicetype=Windows+7&version=62070158&lang=zh_CN&exportkey=AZzgKtDYdvYCRfEV2tkzLUQ%3D&pass_ticket=qUwETpe4qmzZjZi1JD3SOWZ8dM4PBJy2EBiI7dZGF27hw8FimOFXEq0Y4Ig6MLzf

**Comment by gf-huanchupk** [comment]
谢谢，已修复

**Comment by gf-huanchupk** [comment]
@WjF1991 谢谢，已修复。
